# Generated by Django 6.0.2 on 2026-02-24 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_chamdo', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('disciplina', models.CharField(max_length=100)),
                ('local', models.CharField(max_length=150)),
                ('data_prog', models.DateField()),
                ('hh_previstas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('andamento', 'Andamento'), ('concluído', 'Concluído'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('fotos_chamado', models.ImageField(blank=True, null=True, upload_to='solicitacoes/')),
                ('foto_execucao', models.ImageField(blank=True, null=True, upload_to='execucoes/')),
                ('observacao_admin', models.TextField(blank=True)),
                ('observacao_encarregado', models.TextField(blank=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('encarregado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
