# Generated by Django 6.0.2 on 2026-03-16 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_rename_atividades_atividade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('andamento', 'Andamento'), ('concluido', 'Concluido'), ('cancelado', 'Cancelado')], default='pendente', max_length=20),
        ),
    ]
